import {
  Target,
  BarChart3,
  Gauge,
  Star,
  Lightbulb,
  Search,
  Briefcase,
  TrendingUp,
  Link,
  Newspaper,
  Users,
  CheckSquare,
  Calculator,
  FileText,
  RefreshCw,
  CreditCard,
  Scale,
  Calendar,
  Home,
  Bot,
  User,
  Gift,
  HelpCircle,
  DollarSign,
  Gem,
  Medal,
  Flame,
  Sparkles,
  Library,
  XCircle,
  AlertTriangle,
  Shield,
  AlertOctagon,
  Minus,
  ShoppingCart,
  Package,
  Landmark,
  Building2,
  CheckCircle2,
  Trophy,
  Rocket,
  Factory,
  Clock,
  Heart,
  MapPin,
  ClipboardList,
  Dice5,
  SlidersHorizontal,
  CircleAlert,
  CircleMinus,
  CircleCheck,
  Wallet,
  LayoutDashboard,
  type LucideIcon,
} from "lucide-react";

export const ICON_MAP = {
  target: Target,
  barChart: BarChart3,
  gauge: Gauge,
  star: Star,
  lightbulb: Lightbulb,
  search: Search,
  briefcase: Briefcase,
  trendingUp: TrendingUp,
  link: Link,
  newspaper: Newspaper,
  users: Users,
  checkSquare: CheckSquare,
  calculator: Calculator,
  fileText: FileText,
  refreshCw: RefreshCw,
  creditCard: CreditCard,
  scale: Scale,
  calendar: Calendar,
  home: Home,
  bot: Bot,
  user: User,
  gift: Gift,
  helpCircle: HelpCircle,
  dollarSign: DollarSign,
  gem: Gem,
  medal: Medal,
  flame: Flame,
  sparkles: Sparkles,
  library: Library,
  xCircle: XCircle,
  alertTriangle: AlertTriangle,
  shield: Shield,
  alertOctagon: AlertOctagon,
  minus: Minus,
  shoppingCart: ShoppingCart,
  package: Package,
  landmark: Landmark,
  building2: Building2,
  checkCircle: CheckCircle2,
  trophy: Trophy,
  rocket: Rocket,
  factory: Factory,
  clock: Clock,
  heart: Heart,
  mapPin: MapPin,
  clipboardList: ClipboardList,
  dice: Dice5,
  sliders: SlidersHorizontal,
  circleAlert: CircleAlert,
  circleMinus: CircleMinus,
  circleCheck: CircleCheck,
  wallet: Wallet,
  layoutDashboard: LayoutDashboard,
} as const;

export type IconKey = keyof typeof ICON_MAP;

export function getIcon(key: IconKey): LucideIcon {
  return ICON_MAP[key];
}
